### PR TITLE
Fix setup.py/file structure for editable install

### PR DESCRIPTION
**Pull request by gamdow**
Disutils failed to install the packages correctly when doing an editable install (`pip install -e .`). Here's an explanation (https://stackoverflow.com/questions/19602582/pip-install-editable-links-to-wrong-path)

### CODE REVIEW

**Comment by reguly** [comment]
I am not sure how to edit the files myself - could you just search the source tree for scripts that use the translator (e.g. generate.sh in various applications) and modify the path accordingly?

**Comment by gamdow** [comment]
Yup, my bad. This should do the trick.

**Comment by gihanmudalige** [comment]
Do we want to merge this ?

**Comment by reguly** [comment]
Ah, I forgot to do the merge... Apologies

**Pull request merged**
