### PR TITLE
Pull request for a minor fix in the ops C translator 

### PR DESCRIPTION
**Pull request by satyajammy**
Modified ops_gen_mpi_inline.py similar to mpi and CUDA. This allows multiple kernels to be written to the same *.h file.
This is modified as our code is failing to translate when using the translator in the current master branch

### CODE REVIEW

**Comment by gihanmudalige** [comment]
I am looking at this now. Just need to add a test case for the tests scripts.

**Comment by satyajammy** [comment]
There is no test case in the apps repository. But you can check with the OpenSBLI versions I have passed on to you. Once OpenSBLI is released, we will add a couple of test cases. Is that fine?

**Comment by gihanmudalige** [comment]
Jammy, that's fine. I actually meant adding a line to the test.sh to run cloverleaf_mpi_inline. Let me do this quickly and merge your changes.

**Comment by satyajammy** [comment]
OK.

**Pull request merged**
