### PR TITLE
Making a copy of the file name when using hDF5 to declare datasets

### PR DESCRIPTION
**Pull request by reguly**
Causing a crash in Jianping's code.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
I am getting a :

/home/mgiles/mudalige/OPS-GIT/OPS/ops/c/lib/libops_mpi.a(ops_mpi_hdf5.o): In function `ops_decl_dat_hdf5':
src/mpi/ops_mpi_hdf5.c:(.text+0x1a92): undefined reference to `copy_str'

**Comment by jpmeng** [comment]
copy_str() is defined in the ops_utility.c. I would suggest to make it
public for other source files. Thanks. Jianping

**Comment by reguly** [comment]
Links fine now!

**Comment by gihanmudalige** [comment]
It appears that we have an issue with MPI+CUDA for the Fortran applications. The test fails for Poisson. However the same fail occurs in the master branch. So the issue is not due to this pull request. 
Other tests pass without issue.

**Pull request merged**
