### PR TITLE
Fixed multidim mpi exchange issue, removed dead code

### PR DESCRIPTION
**Pull request by reguly**

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Can you have a look at fortran/shsgc  mpi+cuda
I am getting NaN for the solution when it is run some time.

**Comment by gihanmudalige** [comment]
Master seems to be fine.

**Comment by gihanmudalige** [comment]
Perhaps we merge and fix the shsgc fortran mpi+cuda as a separate issue ?

**Comment by reguly** [comment]
I am getting validation failures on the master as well, so the issue appears to be independent. Let’s merge this and fix the shsgc issue separately.

**Pull request merged**
