### PR TITLE
Increasing the number of ops_args in ops_macros.h and ops_mpi_core.h

### PR DESCRIPTION
**Pull request by satyajammy**
Increased the number of args to ops kernel

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Ahh .. you mean changes to ops_mpi_core.c not ops_mpi_core.h  ... yes that's fine

**Comment by gihanmudalige** [comment]
Yes .. this is fine. Do merge.

**Comment by satyajammy** [comment]
Did i say ops_mpi_core.h sorry it was ops_mpi_core.c

**Comment by satyajammy** [comment]
Will you merge it or should I?

**Pull request merged**
