### PR TITLE
Feature/fortran timing

### PR DESCRIPTION
**Pull request by reguly**
Adds timing to Fortran. @gihanmudalige  could you please run the usual tests?

### CODE REVIEW

**Comment by gihanmudalige** [comment]
@reguly , will do.  I am currently setting up some validation tests so that we can take the next step to integrate them to a CI system (with Raz and Ian's help). The scripts should be finished soon. I will merge it to master, rebase this branch on master and then run the tests, if that is ok.

**Comment by reguly** [comment]
Sounds good, thank you!

**Comment by gihanmudalige** [comment]
All applications and parallelizations work except the Fortran _mpi_cuda parallelizations for Poisson and shsgc. The following error occurs: 
0: copyin Symbol Memcpy (dev=0x639420, host=0x7ffdfef5bb58, size=8, offset=0) FAILED: 10(invalid device ordinal)

Using Mcuda=6.0 (as opposed to 7.0) seems to fix this. 
PGI_CUDA_FORT_FLAGS=-Mcuda=cuda6.0,cc35

@reguly should this be working with 7.0 ?

**Comment by reguly** [comment]
Yes it definitely should - what version of the PGI compilers are you using?

**Comment by gihanmudalige** [comment]
Using pgi_15.10

**Comment by reguly** [comment]
Seems to be compiling and running fine for me. 15.10 shouldn’t even support cuda6.0...

**Comment by gihanmudalige** [comment]
Does Poisson_openacc also work for you ?

**Comment by reguly** [comment]
Has it ever worked? It seems to be missing the -acc compiler flag and the openacc pragmas seem off. I’ll take a look and fix it.

**Comment by gihanmudalige** [comment]
Thanks. So I am currently failing tests for the Fortran versions of shsgc_openacc, shsgc_mpi_openacc and poisson_openacc. We also need to build poisson_mpi_openacc and check as well.

**Comment by reguly** [comment]
Did poisson_openacc work before?

**Comment by gihanmudalige** [comment]
Probably not, as it was not caught by my older test script.

**Comment by reguly** [comment]
Let’s postpone fixing OpenACC then, as it’s not in the scope of this merge.

**Comment by gihanmudalige** [comment]
OK, so poisson_mpi_cuda works with Mcuda=7.5. CUDA_INSTALL_PATH was actually /usr/local/cuda-7.5. I guess its this discrepancy that was causing the problem.

**Comment by gihanmudalige** [comment]
Ok, we can postpone fixing the *_openacc an *_mpi_openacc for later. But let me add the -acc flag just for completeness

**Comment by gihanmudalige** [comment]
Ok @reguly you can merge now !

**Comment by reguly** [comment]
Thank you, merging!

**Pull request merged**
