### PR TITLE
Feature/tiling

### PR DESCRIPTION
**Pull request by reguly**
This is pulling the tiling functionality into master. Added to docs, and has a default guess for the tile size.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Testing on Octon now. I will also add new test cases to exercise the tiling functionality.

**Comment by gihanmudalige** [comment]
CloverLeaf and CloverLeaf_3D fails due to the higher optimizations used for ICC. We may need to revert to the exact ones used for validation against the original CloverLeaf applications. Also the use of OpenMP flags in CFLAGS should be separated.

**Comment by reguly** [comment]
Correctied the flags. I have added some OpenMP code to the backend, in particular to Tiling that helps determine the size of tiles. But that only uses omp_get_max_threads, so if we are not compiling with OpenMP, then I have added a substitute function that just looks at the OMP_NUM_THREADS env variable.
I have also added OpenMP code to the halo exchanges, so they can run in parallel - this was particularly slow on OpenSBLI, (when the app used many OMP threads, but the backend didn’t).
But if we are compiling the backend with OpenMP, then we need the openmp compilation flag for all the applications as well.

**Comment by gihanmudalige** [comment]
So the (improved) halo exchange seems to be the only code segment requiring OpenMP (where the tiling can use the alternative without specifying the -qopenmp) ?

**Comment by reguly** [comment]
Yes, but the halo exchange segment can be compiled without openmp fine (you’ll just get some warnings about unrecognised pragmas).

**Comment by gihanmudalige** [comment]
ok. So perhaps we might need a way to inherit the setting of OMPFLAGS in the back end to the applications. I will have a look.

**Comment by gihanmudalige** [comment]
Istvan, I actually could not see the issue where the apps fail to compile without OpenMP flags when the back-end is compiled with OpenMP. Am I missing something ?

**Comment by reguly** [comment]
I have fixed it in the Makefile of the backend, I am no longer compiling the backend with OpenMP flags. But I think that if you do compile the backend with -qopenmp, but not the applicaiton, then you will have issues with linking.

**Comment by gihanmudalige** [comment]
Actually I just did remove the comment on -qopenmp for Intel compiler in the back end Makefile. Then built CloverLeaf 2D and 3D. Did not run into any issues.

**Comment by reguly** [comment]
Hmm, may have been an issue with my setup. Nevertheless, we should probably not compile the backend with OpenMP, as it might lead to unexpected performance issues (launching lots of threads in the block halo exchange on each MPI process), and make a note to users that if they are using lots of OpenMP threads and block halo transfers, recompile the backend.

**Comment by gihanmudalige** [comment]
I will see where this information can be added to. 
Anther issue that has come up in the Tiled version of ColoverLeaf is that when compiling with PGI and #pragma omp simd clause is causing an error. Is there a way to make this Intel "agnostic" ?

**Comment by reguly** [comment]
Hmm, PGI is annoying… I have switched #pragma omp simd to simply #pragma simd, that seems to resolve this. But perhaps won’t vectorise wonderfully on other compilers…

**Comment by gihanmudalige** [comment]
I suppose the code generator for the Tiled version can generate both a #pragma omp simd  AND #pragma simd but ifdef these to be compiled based on the OPS_COMPILER variable ? I am a bit concerned that we will forget that for better performance you need the #pragma omp simd for Intel compiled code

**Comment by gihanmudalige** [comment]
By the way I am almost at the end of fixing various tests and issues for this pull request. We should be able to merge soon.

**Comment by reguly** [comment]
That’s a good point, I pushed a fix for that

**Comment by gihanmudalige** [comment]
Excellent, let me test things out.

**Comment by gihanmudalige** [comment]
Istvan, there is an #undef OPS_GPU in the OpenACC generated code (e.g. CloverLeaf_3D/OpenACC/advec_mom_kernel2_x_openacc_kernel.cpp). Is this correct ?

**Comment by gihanmudalige** [comment]
Testing the Poisson application seems to not give the correct answers. Even with the standard problem and number of blocks (200x200 and 2x2).

**Comment by reguly** [comment]
I am not sure what to do with that - I have slightly modified the stencil, plus given the arbitrary sizes and everything, we don’t have some specific number it should always converge to… Or should we create a specific test case, with a certain size and iterations?

**Comment by gihanmudalige** [comment]
It would be good to have a specific number to test against. I do not mind if this is changed from the current master. Its actually quite easy to set the tests. But the value we are testing against should be correct for all parallelizations.

**Comment by reguly** [comment]
Okay - so I set it to the value that you get without any run-time arguments. seq, openmp, cuda validate well. MPI with 4 procs does not though - I am really not sure why. Can look at this tomorrow as I am heading off to teach.

**Comment by gihanmudalige** [comment]
No problem. Thanks

**Comment by gihanmudalige** [comment]
I think the C apps are now ok. But there are some issues in Fortran apps. Attempting to fix them now

**Comment by gihanmudalige** [comment]
I think we can merge this now.

**Pull request merged**
