### PR TITLE
Fix/fortran and p8

### PR DESCRIPTION
**Pull request by reguly**
Adds p8 support with OPS_COMPILER=xlp8

### CODE REVIEW

**Comment by gihanmudalige** [comment]
The Fortran based Poisson application fails. However the same application in master branch currently gives correct results. Any idea why this is ?

**Comment by reguly** [comment]
There were some experimental modifications to kernels (bugs in CUDA Fortran), and the number of iterations were changed. Should be fixed up now.

**Comment by gihanmudalige** [comment]
Not sure what poisson_test.cuf is for. Should this be deleted ?
poisonn_openacc now segfaults. In master it simply gives the wrong results. see #54

**Comment by reguly** [comment]
Yes, that can be deleted, sorry, I forgot about that. Not sure about OpenACC though…

**Comment by gihanmudalige** [comment]
This is fine to be merged. Just finished all tests (except ones in #54 )

**Comment by gihanmudalige** [comment]
Istvan, is this ok to be merged ?

**Comment by reguly** [comment]
Ah, forgot about this. Merging.

**Pull request merged**
