### PR TITLE
Fix/openacc2

### PR DESCRIPTION
**Pull request by reguly**
Mostly to address issue #54

### CODE REVIEW

**Comment by gihanmudalige** [comment]
The CUDA Fortran version of SHSCG does not compile at the moment -
Illegal number or type of arguments to c_f_pointer errors appear

**Comment by reguly** [comment]
What PGI compiler version are you using? I am using 16.9
Also, -DOP2_WITH_CUDA or similar doesn’t have to be set when compiling - perhaps without it will work.

**Comment by gihanmudalige** [comment]
I am using PGI 15.10. The removing the   -DOP2_WITH_CUDA flag did not work. I will try with a more recent compiler

**Comment by gihanmudalige** [comment]
PGI 16.4 did not work. I cannot use the latest as the site licence does not support it yet. Could you do a quick try on Octon and see if you can recreate my problem.

**Comment by reguly** [comment]
There were some leftover -DOPS_WITH_CUDAFOR flags left int he Makefile of the backend, works now on 16.4 as well.

**Comment by gihanmudalige** [comment]
Tests passed .. should merge this now.

**Pull request merged**
