### PR TITLE
Bug with host side multiple depths exchanges. Added error if halo too…

### PR DESCRIPTION
**Pull request by reguly**
… shallow

### CODE REVIEW

**Comment by gihanmudalige** [comment]
The new commit causes an issue with MPI+OpenACC. The following from test script in CloverLeaf (2D)

============> Running MPI+OpenACC
call to cuStreamSynchronize returned error 700: Illegal address during kernel execution
call to cuMemFreeHost returned error 700: Illegal address during kernel execution

**Comment by reguly** [comment]
Pushed a fix for this, pretty annoying - we have to use OpenACC's device selection...

**Comment by gihanmudalige** [comment]
Did you have any updates to the problem of :  undefined reference to `ops_proc_id

**Comment by reguly** [comment]
Oh, forgot to push it...

**Comment by gihanmudalige** [comment]
There is still some  issue with MPI+OpenACC. Only appears with TeaLeaf : $MPI_INSTALL_PATH/bin/mpirun -np 2 ./tealeaf_mpi_openacc
---
call to cuStreamSynchronize returned error 700: Illegal address during kernel execution

However, CloverLeaf (both 2D and 3D) is fine.

**Comment by reguly** [comment]
We were compiling tea_leaf.cpp instead of tea_leaf_ops.cpp for the code-generated versions. Works now.

**Comment by reguly** [comment]
Thanks Gihan!

**Pull request merged**
