### PR TITLE
Feature/tealeaf

### PR DESCRIPTION
**Pull request by reguly**
This request pulls in the TeaLeaf (2D) application, plus fixes a minor bug (ops_arg_dat_opt in CloverLeaf) and a bandwidth calculation issue in the backend.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Istvan, I will have a look at this soon. I need to add some tests for this app in the scripts. (Start of term has been very busy !)

**Comment by gihanmudalige** [comment]
I have now added tests to check the results. All seems ok. But performance needs to be assessed.

**Comment by reguly** [comment]
Thank you Gihan! Is this okay to be merged?

**Comment by gihanmudalige** [comment]
Yes.. go ahead

**Pull request merged**
