### PR TITLE
Feature/checkpointing2

### PR DESCRIPTION
**Pull request by reguly**
Merging in the latest checkpointing developments

### CODE REVIEW

**Comment by reguly** [comment]
Rebased. Should be orthogonal to any changes in master.
Gihan please take a quick look and let's merge this.

**Comment by gihanmudalige** [comment]
Was attempting to rebase on current master, but there seems to be some considerable conflicts between some older checkpointing code and the latest checkpointing in for e.g. c/src/externlib/ops_checkpointing.c
c/include/ops_checkpointing.h

Did not go ahead with the rebase as I was not sure which version was correct.

**Comment by reguly** [comment]
I am not sure what version you have, perhaps you didn’t fast-forward? But the version up in github is rebased on the current master.

**Comment by gihanmudalige** [comment]
There is a script cloverleaf_checkpoint_move.py in apps/CloverLeaf should this be part of the repo ? If so I can move it into apps/c/CloverLeaf

**Comment by reguly** [comment]
I guess it should be - it’s for moving checkpoint files from one place to another; e.g. from local storage to shared.

**Comment by gihanmudalige** [comment]
It seems poisson_mpi_openacc is breaking with more than 1 MPI proc. Unfortunately it seems to break in the current master as well. But I do remember it working a couple of months ago.

**Comment by gihanmudalige** [comment]
I think this is fine to be merged, but needs another rebase on master.

**Pull request merged**
