### PR TITLE
Fix an issue when exporting MultiDim data to HDF5  in the parallel mode.

### PR DESCRIPTION
**Pull request by jpmeng**
The fixed issue causing the following complaints from HDF5 routines:
h5dwrite(): file selection+offset not within extent
and then the HDF5 routine refuses to write the actual data.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Jianping, can you do the changes you mentioned (i.e. get the other routines consistent as well). Then we can test out on the HDF5 based applications and see if this is ok.

**Comment by jpmeng** [comment]
Ok. Please allow me sometime. I will aim to finish it within next week. Jianping

**Comment by jpmeng** [comment]
Hi Gihan,

I have corrected issues that I can see. Please have a test. 

Jianping

**Comment by gihanmudalige** [comment]
Thanks for this. I have been having a look. 
CloverLeaf_3D_HDF5 gives the correct numerical results but the we get 
Error: ops_fetch_dat_hdf5_file: Unequal d_p of data set density1: g_d_p[0] on file 9, g_d_p[0] to be wirtten 2

This only happens with the following sequence of commands:

rm *.h5
./generate_file  
KMP_AFFINITY=compact OMP_NUM_THREADS=20 ./cloverleaf_openmp
export OMP_NUM_THREADS=2;$MPI_INSTALL_PATH/bin/mpirun -np 10 ./cloverleaf_mpi_openmp

This error seems to be present in the master branch as well, so I am having a look at why this is happening.

**Comment by jpmeng** [comment]
Gihan,

Thanks. 

It appears something wrong with probably both the reading and writing of halo points? So far, I just test the routines for writing in 2D problems, the code appears to be able to work fine with d_p==d_m==1. 

There is another issue I forgot mention: if there is an existing file in the directory, the code seems not to update the data in that file. Not sure if it is just the purpose or something wrong. I found this quite long ago, and then ask the code to writing to a new file for each output. So not sure if it is still there. 

Cheers,

Jianping

**Comment by gihanmudalige** [comment]
I have implemented a fix for the error: 
Error: ops_fetch_dat_hdf5_file: Unequal d_p of data set density1: g_d_p[0] on file 9, g_d_p[0] to be wirtten 2

@jpmeng can you take a look at this branch and see if your applications are working OK with it.

**Comment by gihanmudalige** [comment]
@jpmeng  Did you have a chance to test this out ?
Thanks.

**Comment by jpmeng** [comment]
Gihan, Sorry for late response.  What did you mean by test? My code seems fine. Jianping

**Pull request merged**
