### PR TITLE
Fix/fortran3d

### PR DESCRIPTION
**Pull request by reguly**
Pulls in a number of fixes for Fortran and 3D support, including finding functions called from within user kernels in Fortran CUDA. I have also added checks for non-0 point stencils that are written and which are invalid according to the OPS abstraction. However, this breaks CloverLeaf's generate_chunk - it has to be reformulated.

### CODE REVIEW

**Comment by reguly** [comment]
@gihanmudalige I pushed a fix for generate_chunk, could you please run the usual tests on CloverLeaf and CloverLeaf_3D (and anything else we usually do)?

**Comment by gihanmudalige** [comment]
CloverLeaf_3D_HDF5 needs to be updated with this fix, I can do this. Also shsgc breaks with this update. Perhaps @satyajammy  can fix shsgc ?

**Comment by reguly** [comment]
The shsgc bug appearsh to have only been a typo, it’s not actually using those extra points, I have fixed that in both C and Fortran. I have also modified the HDF5 cloverleaf.

**Comment by gihanmudalige** [comment]
Great. I am testing the libs and apps now.

**Comment by satyajammy** [comment]
Yes, it is a typo. We are not using the extra points.

**Comment by gihanmudalige** [comment]
This can be merged now

**Comment by gihanmudalige** [comment]
@reguly There is an error in the fortran python code generator : 
File "/home/mgiles/mudalige/OPS-GIT/OPS/translator/python/fortran/ops_fortran_gen_mpi_cuda.py", line 63, in replace_consts
    fi2 = open("constants_list.txt","r")
IOError: [Errno 2] No such file or directory: 'constants_list.txt'

**Comment by gihanmudalige** [comment]
There are still some errors, but they seem to have originated from a previous pull request. Let me fix these and then merge.

**Comment by reguly** [comment]
I have pushed a fix for the constants_list.txt not found issue - but I am adding the implementation of ops_decl_const as an outstanding issue, as we need to properly handle this.

**Comment by gihanmudalige** [comment]
Could you do a quick run of the 2nd Fortran version of Multidim and see if the Cuda parallelisation gives the same result sa the seq? Not sure if there is an issue with Octon.
Thanks


Sent from my Ultrafast Samsung Galaxy S4 Mini on Three


-------- Original message --------
From: Istvan Reguly
Date:11/05/2016 19:05 (GMT+00:00)
To: gihanmudalige/OPS
Cc: Gihan Mudalige , Mention
Subject: Re: [gihanmudalige/OPS] Fix/fortran3d (#51)

I have pushed a fix for the constants_list.txt not found issue - but I am adding the implementation of ops_decl_const as an outstanding issue, as we need to properly handle this.

**Comment by reguly** [comment]
Both multiDim and multiDim3D seem to be giving the same reduction result: the first 40, the second 160l

**Comment by gihanmudalige** [comment]
OK Seems to have been a glitch with Octon. A reboot have fixed it.

**Comment by gihanmudalige** [comment]
I think this can be merged now.

**Pull request merged**
