### PR TITLE
Power8 support with OPS_COMPILER=xlp8

### PR DESCRIPTION
**Pull request by reguly**

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Is there a new code generator for this ?

**Comment by reguly** [comment]
Yes, it is called ops_gen_mpi_inline.py, it actually inlines the user kernel into the loop nest - this is perhaps something worth using for other purposes as well. Has no performance impact on Intel though.

**Comment by gihanmudalige** [comment]
Sorry, did no see that on the initial pull request.

**Comment by gihanmudalige** [comment]
Is this pull request ready to be merged ?

**Comment by reguly** [comment]
Not quite - I'll still have to rebase it and add compiler support for XL CUDA Fortran...

Cheers,
István

**Pull request closed without merging**
