### PR TITLE
Handle CUDA complex numbers

### PR DESCRIPTION
**Pull request by ctjacobs**
Modifies the OPS translator such that `double __complex__ foo = 2.0 - 1.0I` is replaced with the CUDA call `cuDoubleComplex foo = make_cuDoubleComplex(2.0, -1.0);`, for example. Also handles `__real__`, `__imag__` and multiplication of two complex variables.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Hi Christian,  I am just about to merge this in. But is there a small test case that you can add as a unit test for the functionality ?

**Comment by gihanmudalige** [comment]
@ctjacobs  ... Do you have a test that utilises this function ?

**Comment by ctjacobs** [comment]
I've just added an example in `apps/c/complex_numbers` - it doesn't check the simulation's result (it doesn't really simulate anything realistic) but it's more to check that the OPS translator can convert complex number related function calls.

**Comment by gihanmudalige** [comment]
@ctjacobs .. Thanks. I will have a look

**Comment by gihanmudalige** [comment]
@ctjacobs The example applications for complex-numbers are all compiling  except for the openacc version. Have you ever tested this out ?

**Comment by ctjacobs** [comment]
No, I don't have `acc` installed here. What's the error message?

**Comment by gihanmudalige** [comment]
Seems the error is comming from OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c


/opt/openmpi-1.8.4-pgi151//bin/mpicc -acc -ta=tesla:cc35 -ta=tesla:maxregcount:64 -O3 -Kieee -Minline -Minform=severe -Minfo=all -D__x86_64 -D__align__\(n\)=__attribute__\(\(aligned\(n\)\)\) -D__location__\(a\)=__annotate__\(a\) -DCUDARTAPI= -I/home/mgiles/mudalige/OPS-GIT/OPS/ops/c/include -DCHECKPOINTING -I/opt/hdf5-pgi//include -I/usr/local/cuda-6.5.14//include \
        -I. OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c -c -L/opt/hdf5-pgi//lib -lhdf5_hl -lhdf5 -lz -o OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.o
PGC-S-0029-Syntax error: Recovery attempted by deleting from identifier z on line 17 to just before ';' on line 17 (OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c: 17)
PGC-S-0043-Redefinition of symbol, __complex__ (OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c: 18)
PGC-S-0029-Syntax error: Recovery attempted by deleting from identifier coeff on line 18 to just before ';' on line 18 (OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c: 18)
PGC-S-0039-Use of undeclared variable coeff (OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c: 21)
PGC-S-0039-Use of undeclared variable z (OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c: 21)
PGC-S-0039-Use of undeclared variable coeff (OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c: 21)
PGC-S-0037-Syntax error: Recovery attempted by deleting identifier __real__ (OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c: 22)
PGC-S-0037-Syntax error: Recovery attempted by deleting identifier __imag__ (OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel_c.c: 23)
PGC/x86-64-Extractor Linux 15.1-0: completed with severe errors
make: *** [OpenACC/complex_numbers_block0_cn_kernel_openacc_kernel.o] Error 2

**Comment by ctjacobs** [comment]
Can we just remove the OpenACC test for now, since this PR only deals with CUDA? I haven't changed anything in the OpenACC part of the translator, so I assume OPS complex number support has never been there for OpenACC anyway.

**Pull request merged**
